[package]
name = "pong_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
raylib = "3.7.0"
regex= "1.10.4"
rand = "0.8.5"
serde = "1.0.204"
